version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on: []
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://10.20.2.69:1433;databaseName=ecl_agrisasa_db;encrypt=false;
      - SPRING_DATASOURCE_USERNAME=dcharo
      - SPRING_DATASOURCE_PASSWORD=ghyyddtau
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect
    ports:
      - "8085:8086"
